# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 11:33
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0012_auto_20170401_1120'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.uid')),
                ('accno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.accounts')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shareCount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('sharePrice', models.DecimalField(decimal_places=2, max_digits=20)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup.StartupProfile')),
            ],
        ),
    ]
