# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupprofile',
            name='aadhar',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.uid'),
        ),
        migrations.AlterField(
            model_name='startupprofile',
            name='accno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.accounts'),
        ),
    ]
