# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startupprofile',
            old_name='account',
            new_name='accountInfo',
        ),
    ]
