# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0002_auto_20170401_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupprofile',
            name='startupName',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
