# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0004_auto_20170405_1319'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='startupprofile',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='startupprofile',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='startupprofile',
            name='ifsc',
        ),
    ]
