# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 11:39
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0012_auto_20170401_1120'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('startup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='holdings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shareCount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='InvestorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.uid')),
                ('accno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.accounts')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='holdings',
            name='shareHolder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investor.InvestorProfile'),
        ),
        migrations.AddField(
            model_name='holdings',
            name='startupName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup.StartupProfile'),
        ),
    ]
