# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 14:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_auto_20170405_1428'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.uid')),
                ('accountInfo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.accounts')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
