# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holdings',
            name='shareHolder',
        ),
        migrations.RemoveField(
            model_name='holdings',
            name='startupName',
        ),
        migrations.DeleteModel(
            name='holdings',
        ),
    ]
