# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0004_auto_20170405_1319'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='investorprofile',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='investorprofile',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='investorprofile',
            name='ifsc',
        ),
    ]
