# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investor', '0002_auto_20170401_1206'),
        ('startup', '0003_startupprofile_startupname'),
    ]

    operations = [
        migrations.CreateModel(
            name='holdings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shareCount', models.IntegerField()),
                ('investorName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investor.InvestorProfile')),
                ('stockName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup.StartupProfile')),
            ],
        ),
        migrations.CreateModel(
            name='onSaleInvestor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sharePrice', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investor.InvestorProfile')),
                ('shareCount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.holdings')),
            ],
        ),
        migrations.CreateModel(
            name='onSaleStartup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shareCount', models.IntegerField()),
                ('sharePrice', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup.StartupProfile')),
            ],
        ),
    ]
