# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('startup', '0001_initial'),
        ('investor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='holdings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shareCount', models.IntegerField()),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investor.InvestorProfile')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup.StartupProfile')),
            ],
        ),
        migrations.CreateModel(
            name='onSaleInvestor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shareCount', models.IntegerField()),
                ('sharePrice', models.IntegerField()),
                ('holdings1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.holdings')),
            ],
        ),
        migrations.CreateModel(
            name='onSaleStartup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shareCount', models.IntegerField()),
                ('sharePrice', models.IntegerField()),
                ('holdings2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup.StartupProfile')),
            ],
        ),
    ]
