# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 08:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onsaleinvestor',
            old_name='stockName',
            new_name='holdings1',
        ),
        migrations.RenameField(
            model_name='onsalestartup',
            old_name='stockName',
            new_name='holdings',
        ),
    ]
