# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onsaleinvestor',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.holdings'),
        ),
        migrations.AlterField(
            model_name='onsaleinvestor',
            name='shareCount',
            field=models.IntegerField(),
        ),
    ]
