# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 08:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20170402_0839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onsalestartup',
            old_name='holdings',
            new_name='holdings2',
        ),
    ]
