# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20170401_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onsaleinvestor',
            old_name='owner',
            new_name='stockName',
        ),
    ]
