# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 21:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20170402_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holdings',
            name='investor',
        ),
        migrations.RemoveField(
            model_name='holdings',
            name='startup',
        ),
        migrations.RemoveField(
            model_name='onsaleinvestor',
            name='holdings1',
        ),
        migrations.RemoveField(
            model_name='onsalestartup',
            name='holdings2',
        ),
        migrations.DeleteModel(
            name='holdings',
        ),
        migrations.DeleteModel(
            name='onSaleInvestor',
        ),
        migrations.DeleteModel(
            name='onSaleStartup',
        ),
    ]
