# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 15:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0004_auto_20170405_1319'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0003_auto_20170402_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockpercentage', models.FloatField()),
                ('stockprice', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup.StartupProfile')),
            ],
        ),
    ]
