# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='bankName',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accounts',
            name='ifsc',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
