# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='bank',
            new_name='bankName',
        ),
    ]
