# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170328_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accno', models.CharField(max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='uid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar', models.CharField(max_length=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='inv',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='inv',
            name='holdings',
        ),
        migrations.RemoveField(
            model_name='sp',
            name='uid',
        ),
        migrations.AddField(
            model_name='inv',
            name='aadhar',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.uid'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inv',
            name='accno',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.accounts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sp',
            name='aadhar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.uid'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sp',
            name='accno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.accounts'),
            preserve_default=False,
        ),
    ]
