# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170329_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inv',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
