# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170329_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='holdings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shareCount', models.IntegerField()),
                ('invName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inv')),
                ('soName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Sp')),
            ],
        ),
        migrations.CreateModel(
            name='stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shareCount', models.IntegerField()),
                ('sharePrice', models.DecimalField(decimal_places=2, max_digits=20)),
                ('soName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Sp')),
            ],
        ),
    ]
