# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 16:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_holdings_stocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdings',
            name='shareCount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='shareCount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
