# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 14:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_auto_20170330_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.uid')),
                ('accno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.accounts')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
