# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170401_0956'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sp',
            new_name='StartupProfile',
        ),
    ]
