# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 10:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_auto_20170401_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holdings',
            old_name='invName',
            new_name='shareHolder',
        ),
        migrations.RenameField(
            model_name='holdings',
            old_name='soName',
            new_name='startupName',
        ),
        migrations.RenameField(
            model_name='stocks',
            old_name='soName',
            new_name='startup',
        ),
        migrations.RemoveField(
            model_name='investorprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='startupprofile',
            name='name',
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='user',
            field=models.OneToOneField(default=b'', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='startupprofile',
            name='user',
            field=models.OneToOneField(default=b'', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='investorprofile',
            name='aadhar',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='app.uid'),
        ),
        migrations.AlterField(
            model_name='investorprofile',
            name='accno',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='app.accounts'),
        ),
        migrations.AlterField(
            model_name='startupprofile',
            name='aadhar',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='app.uid'),
        ),
        migrations.AlterField(
            model_name='startupprofile',
            name='accno',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='app.accounts'),
        ),
    ]
