# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 10:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20170401_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorprofile',
            name='aadhar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.uid'),
        ),
        migrations.AlterField(
            model_name='investorprofile',
            name='accno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.accounts'),
        ),
        migrations.AlterField(
            model_name='investorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='startupprofile',
            name='aadhar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.uid'),
        ),
        migrations.AlterField(
            model_name='startupprofile',
            name='accno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.accounts'),
        ),
        migrations.AlterField(
            model_name='startupprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
