# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20170401_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holdings',
            name='shareHolder',
        ),
        migrations.RemoveField(
            model_name='holdings',
            name='startupName',
        ),
        migrations.RemoveField(
            model_name='investorprofile',
            name='aadhar',
        ),
        migrations.RemoveField(
            model_name='investorprofile',
            name='accno',
        ),
        migrations.RemoveField(
            model_name='investorprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='startupprofile',
            name='aadhar',
        ),
        migrations.RemoveField(
            model_name='startupprofile',
            name='accno',
        ),
        migrations.RemoveField(
            model_name='startupprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='startup',
        ),
        migrations.DeleteModel(
            name='holdings',
        ),
        migrations.DeleteModel(
            name='InvestorProfile',
        ),
        migrations.DeleteModel(
            name='StartupProfile',
        ),
        migrations.DeleteModel(
            name='stocks',
        ),
    ]
